# install required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|

	config.vm.define "app" do |app|
		# creating a virtual machine ubuntu
		app.vm.box = "ubuntu/xenial64"

		# let's attach a private network with IP
		app.vm.network "private_network", ip: "192.168.10.100"
		app.hostsupdater.aliases = ["development.local"]
		app.vm.provision "shell", inline: "sudo echo 'export DB_HOST=mongodb://192.168.10.200:27017/posts' >> /etc/profile.d/myvars.sh", run: "always"
		
		# to transfer files/folders from our OS to VM vagrant has an option os synced_folder
		app.vm.synced_folder ".", "/home/vagrant/app"
		
		app.vm.provision "shell", path: "provision_app.sh"

	end

	config.vm.define "db" do |db|
		# creating a virtual machine ubuntu
		db.vm.box = "ubuntu/xenial64"

		# let's attach a private network with IP
		db.vm.network "private_network", ip: "192.168.10.200"
		db.hostsupdater.aliases = ["database.local"]
		
		# to transfer files/folders from our OS to VM vagrant has an option os synced_folder
		db.vm.synced_folder ".", "/home/vagrant/db"
		
		db.vm.provision "shell", path: "provision_db.sh"		
		
	end

end
